version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog_db
